name: Build and Push Tagged csi-s3

on:
  push:
    tags: ["*"]

jobs:
  build-amd64:
    runs-on: debian-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          ref: master
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: git.gmem.ca/arch/csi-s3:${{ github.ref_name }}-amd64,ghcr.io/gmemstr/csi-s3:${{ github.ref_name }}-amd64

  build-arm64:
    runs-on: debian-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          ref: master
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: git.gmem.ca/arch/csi-s3:${{ github.ref_name }}-arm64,ghcr.io/gmemstr/csi-s3:${{ github.ref_name }}-arm64

  merge:
    needs: [build-amd64, build-arm64]
    runs-on: debian-latest
    steps:
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Merge and push manifest
        run: |
          docker manifest create git.gmem.ca/arch/csi-s3:${{ github.ref_name }} \
            --amend git.gmem.ca/arch/csi-s3:${{ github.ref_name }}-amd64 \
            --amend git.gmem.ca/arch/csi-s3:${{ github.ref_name }}-arm64
          docker manifest push git.gmem.ca/arch/csi-s3:${{ github.ref_name }}
          echo "Mirroring to ghcr.io"
          docker manifest create ghcr.io/gmemstr/csi-s3:${{ github.ref_name }} \
            --amend ghcr.io/gmemstr/csi-s3:${{ github.ref_name }}-amd64 \
            --amend ghcr.io/gmemstr/csi-s3:${{ github.ref_name }}-arm64
          docker manifest push ghcr.io/gmemstr/csi-s3:${{ github.ref_name }}
