name: Test csi-s3

on:
  push:

jobs:
  test:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make test
